name: prod build and deploy

# 向主干main分支推送代码时触发部署
on:
  push:
    branches:
      - main

jobs:
  prod-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.5.0'

      - name: Install dependencies
        run: npm install

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Build project
        run: npm run build

      - name: Deploy to EdgeOne Pages
        env:
          EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}
        run: |
          echo "Deploying to EdgeOne Pages..."
          npx edgeone pages deploy ./public -n tragicmaster-personal-blog -t ${{ secrets.EDGEONE_API_TOKEN }} -e production
        